### ISSUE TITLE
Does this work still?

### ISSUE THREAD

**Issue by daviddias** [whyrusleeping/libp2p-examples#1]
I believe it doesn't, now that a bunch of things were modularised.

**Comment by whyrusleeping** [comment]
@diasdavid yeah, i'm going to have to update it now.

**Comment by daviddias** [comment]
Thank you :) <3

**Comment by george-angel** [comment]
Hello, any update on this? Trying to build you get errors, substituting deps, leads to more errors. Would love you have a working example, tyvm.

**Comment by whyrusleeping** [comment]
waiting on this to merge: https://github.com/jbenet/go-stream-muxer/pull/6

Once thats in, and i rewrite a few paths, everything should be good again

**Comment by daviddias** [comment]
@whyrusleeping seems that https://github.com/jbenet/go-stream-muxer/pull/6 was merged. Can these be updated, please?

**Comment by whyrusleeping** [comment]
@diasdavid i've updated this so that it works now

**Comment by daviddias** [comment]
thank you :)
