### ISSUE TITLE
Interop testing with js-libp2p

### ISSUE THREAD

**Issue by daviddias** [whyrusleeping/libp2p-examples#3]
In order to get interop, one of my attempts is to get the basic examples of js-libp2p to work with go-libp2p. The basic example is:
- Two libp2p nodes
- Both have spdy + identify enabled
- One mounts the 'echo' protocol
- The other dials on the echo protocol and writes something to be echoed

So far, I haven't been successful achieve this, here is the latest two attempts

**`go dialer, js listener`**

![image](https://cloud.githubusercontent.com/assets/1211152/15399567/1ae2a194-1de0-11e6-81a1-3edb0d9e7ba3.png)

**`go listener, js dialer`**

![image](https://cloud.githubusercontent.com/assets/1211152/15399588/3907c50a-1de0-11e6-86df-31a1fab34cef.png)

**Comment by daviddias** [comment]
I'm not seeing where I can select the protocol on the go-libp2p, however, the thing that concerns me is the fact that it says that the protocol is not supported when dialing from go to node. Is secio turned by default in these examples?

**Comment by daviddias** [comment]
The js code for these examples can be found https://github.com/ipfs/js-libp2p-ipfs/tree/master/examples/echo

**Comment by whyrusleeping** [comment]
@diasdavid yeah, i think those examples use secio by default. Let me look at making that optional

**Comment by daviddias** [comment]
Status update: We've solved the SPDY issue.

Next: finishing the tests.

![image](https://cloud.githubusercontent.com/assets/1211152/15426312/a0be89ae-1e85-11e6-8819-7f293f33c4af.png)

![image](https://cloud.githubusercontent.com/assets/1211152/15426318/a7ea1c48-1e85-11e6-909d-94e850c07528.png)

Right now identify seems to be working, we just need to make the tests more verbose so that we now what is going on :)

Also, go-ipfs likes do blow up SPDY when it doesn't want to talk with the peer anymore. We need to listen for RST frames and just delete it from our pool of muxed conns in Swarm

**Comment by paralin** [comment]
Was there any progress on this front?
